import {NextRequest,NextResponse} from "next/server";
import {getAdminSupabase,requireAdmin} from "@/lib/server";
import {isEquipment} from "@/lib/equipment";

export async function GET(req:NextRequest){try{await requireAdmin(req);const {data,error}=await getAdminSupabase().from("maintenance_blocks").select("*").order("start_time",{ascending:false}).limit(200);if(error)throw error;return NextResponse.json({blocks:data||[]})}catch(e:any){return fail(e)}}
export async function POST(req:NextRequest){try{const admin=await requireAdmin(req);const body=await req.json();const valid=validate(body);if(valid)return valid;const {data,error}=await getAdminSupabase().from("maintenance_blocks").insert({equipment:body.equipment,title:String(body.title).trim(),reason:String(body.reason||"").trim(),start_time:new Date(body.start).toISOString(),end_time:new Date(body.end).toISOString(),created_by:admin.id}).select().single();if(error)throw error;return NextResponse.json({ok:true,block:data})}catch(e:any){return fail(e)}}
export async function PATCH(req:NextRequest){try{await requireAdmin(req);const body=await req.json();if(!body.id)return NextResponse.json({error:"Block ID is required."},{status:400});const valid=validate(body);if(valid)return valid;const {data,error}=await getAdminSupabase().from("maintenance_blocks").update({equipment:body.equipment,title:String(body.title).trim(),reason:String(body.reason||"").trim(),start_time:new Date(body.start).toISOString(),end_time:new Date(body.end).toISOString(),updated_at:new Date().toISOString()}).eq("id",body.id).select().single();if(error)throw error;return NextResponse.json({ok:true,block:data})}catch(e:any){return fail(e)}}
export async function DELETE(req:NextRequest){try{await requireAdmin(req);const id=req.nextUrl.searchParams.get("id");if(!id)return NextResponse.json({error:"Block ID is required."},{status:400});const {error}=await getAdminSupabase().from("maintenance_blocks").delete().eq("id",id);if(error)throw error;return NextResponse.json({ok:true})}catch(e:any){return fail(e)}}
function validate(b:any){if(!isEquipment(b.equipment)||!String(b.title||"").trim()||!b.start||!b.end)return NextResponse.json({error:"Equipment, title, start, and end are required."},{status:400});if(!(new Date(b.end)>new Date(b.start)))return NextResponse.json({error:"End time must be later than start time."},{status:400});return null}
function fail(e:any){console.error(e);return NextResponse.json({error:e.message==="ADMIN_REQUIRED"?"Admin access required.":"Could not manage maintenance blocks."},{status:e.message==="ADMIN_REQUIRED"?403:500})}
